version: '3.1'

services:
  pms-backend:
    image: openjdk:11.0.11-jdk-slim
    container_name: pms-backend
    restart: always
    command: "java -Dspring.profiles.active=release -jar /usr/src/jar/open-dashboard-server-0.0.1-SNAPSHOT.jar"
    ports:
      - "8200:8310" # 외부:내부 포트. 8200이 외부로 노출되고 8310으로 내부 전달됨
    volumes:
      - /swhome/pms/pms-backend/volume/jar:/usr/src/jar
      - /swhome/pms/pms-frontend/volume/nginx/html/attachments:/project/openDashBoardFront/dist/attachments # 첨부파일
      - /swhome/pms/pms-frontend/volume/nginx/html/profile/images:/project/openDashBoardFront/dist/profile/images # 프로필 이미지
      - /swhome/pms/pms-backend/volume/logs:/project/logs # 로그
    networks:
      - pms-network
networks:
  pms-network:
    # 다른컨테이너(프론트)와 동일한 네트워크를 사용하기 위해 외부 네트워크로 설정
    external: true