version: '3.1'

services:
  pms-frontend:
    image: nginx:1.23.3-alpine
    container_name: pms-frontend
    ports:
      - 8210:8210
    environment:
      #      - NGINX_PORT=80
      - TZ=Asia/Seoul
    volumes:
      - /swhome/pms/pms-frontend/volume/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /swhome/pms/pms-frontend/volume/nginx/conf.d:/etc/nginx/conf.d
      - /swhome/pms/pms-frontend/volume/nginx/html:/usr/share/nginx/html-www
      - /swhome/pms/pms-frontend/volume/logs:/var/log/nginx/www
    networks:
      - pms-network
networks:
  pms-network:
    # 서버(백엔드)와 동일한 네트워크를 사용하기 위해 외부 네트워크로 설정
    external: true