FROM composer:1.9.3 as vendor

WORKDIR /tmp/

COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist


FROM php:7.2-apache

# RUN apt-get install -y libpng12-dev libjpeg-dev
# RUN apt-get install -y mysql-client
# RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
# && docker-php-ext-install gd

RUN apt-get update
RUN apt-get install --yes --force-yes cron g++ gettext libicu-dev openssl libc-client-dev libkrb5-dev libxml2-dev libfreetype6-dev libgd-dev libmcrypt-dev bzip2 libbz2-dev libtidy-dev libcurl4-openssl-dev libz-dev libmemcached-dev libxslt-dev

RUN a2enmod rewrite

RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install mysqli 
RUN docker-php-ext-enable mysqli

# RUN docker-php-ext-configure gd --with-freetype=/usr --with-jpeg=/usr
RUN docker-php-ext-install gd
COPY . /var/www/html
COPY --from=vendor /tmp/vendor/ /var/www/html/vendor/